# Generated by Django 4.2.2 on 2023-07-25 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataset_info',
            fields=[
                ('dataset_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='gene_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gene_name', models.CharField(max_length=50)),
                ('gene_ensg', models.CharField(blank=True, max_length=50, null=True)),
                ('gene_annotation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='literature_info',
            fields=[
                ('pmid', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('publication', models.CharField(blank=True, max_length=50, null=True)),
                ('relase_time', models.DateField(blank=True, null=True)),
                ('article_title', models.CharField(blank=True, max_length=255, null=True)),
                ('article_url', models.URLField(blank=True, null=True)),
                ('articel_abstract', models.TextField(blank=True, null=True)),
                ('articel_content', models.TextField(blank=True, null=True)),
                ('has_usefull_dataset', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='literature_dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_url', models.URLField(blank=True, null=True)),
                ('dataset_path', models.FilePathField(blank=True, null=True)),
                ('used_method', models.CharField(blank=True, max_length=50, null=True)),
                ('species_name', models.CharField(blank=True, max_length=50, null=True)),
                ('tissue_name', models.CharField(blank=True, max_length=50, null=True)),
                ('cell_types', models.TextField(blank=True, null=True)),
                ('num_cells', models.IntegerField(blank=True, null=True)),
                ('markers_main', models.TextField(blank=True, null=True)),
                ('markers_other', models.TextField(blank=True, null=True)),
                ('dataset_info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celldb_v2.dataset_info')),
                ('literature_info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celldb_v2.literature_info')),
            ],
        ),
        migrations.CreateModel(
            name='gene_expression',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gene_name', models.CharField(blank=True, max_length=50, null=True)),
                ('expression', models.JSONField(blank=True, null=True)),
                ('dataset_info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celldb_v2.dataset_info')),
            ],
        ),
        migrations.AddField(
            model_name='dataset_info',
            name='literature',
            field=models.ManyToManyField(blank=True, through='celldb_v2.literature_dataset', to='celldb_v2.literature_info'),
        ),
        migrations.CreateModel(
            name='cell_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('cell_type', models.CharField(blank=True, max_length=100, null=True)),
                ('ncount_rna', models.FloatField(blank=True, null=True)),
                ('nfeature_rna', models.FloatField(blank=True, null=True)),
                ('percent_mt', models.FloatField(blank=True, null=True)),
                ('umap_1', models.FloatField(blank=True, null=True)),
                ('umap_2', models.FloatField(blank=True, null=True)),
                ('dataset_info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celldb_v2.dataset_info')),
            ],
        ),
    ]
