# Generated by Django 4.2.2 on 2023-07-25 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celldb_v2', '0002_rename_dataset_info_id_literature_dataset_dataset_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='literature_info',
            old_name='relase_time',
            new_name='release_time',
        ),
    ]
