# Generated by Django 4.2.1 on 2023-05-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StuInfo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("age", models.IntegerField()),
                ("grade", models.CharField(max_length=20)),
            ],
        ),
    ]
