# Generated by Django 4.2.1 on 2023-05-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celldb", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stu",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("grade", models.IntegerField(blank=True, null=True)),
            ],
            options={"db_table": "Stu", "managed": False,},
        ),
    ]
