# Generated by Django 4.2.1 on 2023-06-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celldb', '0002_stu'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranMeta',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('cell_barcode', models.CharField(max_length=255)),
                ('cell_type', models.CharField(max_length=255)),
                ('zone', models.IntegerField()),
                ('run_id', models.CharField(max_length=255)),
                ('time_point', models.IntegerField()),
                ('umap_x', models.FloatField()),
                ('umap_y', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='StuInfo',
        ),
        migrations.DeleteModel(
            name='Stu',
        ),
    ]
