# Generated by Django 4.2.1 on 2023-06-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("celldb", "0004_datasetmeta"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiteratureMeta",
            fields=[
                (
                    "Liter_pmid",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "Liter_title",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("Liter_abstract", models.TextField(blank=True, null=True)),
                ("Liter_publication", models.TextField(blank=True, null=True)),
                ("Liter_content", models.TextField(blank=True, null=True)),
                ("Liter_data", models.TextField(blank=True, null=True)),
                ("Sample_info", models.TextField(blank=True, null=True)),
                ("Species", models.CharField(blank=True, max_length=100, null=True)),
                ("Tissue", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "Number_cells",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("Cell_types", models.CharField(blank=True, max_length=100, null=True)),
                ("Method", models.CharField(blank=True, max_length=100, null=True)),
                ("Markers", models.CharField(blank=True, max_length=1000, null=True)),
                ("Note", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
